CREATE DATABASE IF NOT EXISTS logindb;

USE logindb;

CREATE USER 'cylang'@'logindb' IDENTIFIED BY '7:2,M4AytU:Rf7';

GRANT ALL PRIVILEGES ON logindb.* TO 'cylang'@'logindb';

FLUSH PRIVILEGES;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    pass VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    domicile VARCHAR(100) NOT NULL
);

CREATE TABLE enc(
    encID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usrID INT NOT NULL,
    encStr VARCHAR(300) NOT NULL,
    plnStr VARCHAR(300) NOT NULL,
    typeEnc VARCHAR(20) NOT NULL
);

CREATE TABLE dcr(
    decID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    usrID INT NOT NULL,
    decStr VARCHAR(300) NOT NULL,
    plnStr VARCHAR(300) NOT NULL,
    typeEnc VARCHAR(20) NOT NULL
);