version: '3'

services:
  cylang_php:
    build: 
      context: .
      dockerfile: php_docker.Dockerfile
    container_name: cylang_main
    ports:
      - 3738:80
  cylang_db:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    build:
      context: .
      dockerfile: mysql_docker.Dockerfile
    container_name: cylang_login_db
    ports: 
      - 7374:33060
    restart: always